#!/usr/bin/env bash

chosen=$(printf "󰐦  Power Off\n󰜉  Restart\n󰍁  Lock\n󰒲  Suspend" | rofi -dmenu -i -theme-str '@import "config.rasi"')

case "$chosen" in
	"󰐦  Power Off") poweroff ;;
	"󰜉  Restart") reboot ;;
	"󰍁  Lock") slock ;;
	"󰒲  Suspend") sudo systemctl suspend ;;
	*) exit 1 ;;
esac
